In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

train=pd.read_csv('train_imputed.csv').drop('Unnamed: 0',axis=1)
test=pd.read_csv('test_imputed.csv').drop('Unnamed: 0',axis=1)

In [2]:
train.head()

ID  Age  Recently_upskilled     Region  RemoteWork  \
0   45298   33                   0    Chennai           0   
1  172630   34                   1  Delhi NCR           0   
2   63754   33                   1    Chennai           0   
3  107105   38                   0  Delhi NCR           0   
4  173095   28                   1  Hyderabad           0   

   PercentSalaryIncrement  OfficeHours  StockOptionLevel  College_Tier  \
0                      15            9                 1           2.0   
1                      16            7                 0           2.0   
2                      14            7                 0           2.0   
3                      10            7                 1           2.0   
4                      16            7                 0           2.0   

   YearsSinceLastPromotion  ... Department EnvironmentSatisfaction1  \
0                      1.0  ...        Ops                      3.0   
1                      0.0  ...    Finance                      2.0   
2                      1.0  ...      Sales                      3.0   
3                      1.0  ...      Sales                      4.0   
4                      0.0  ...      Sales                      1.0   

   EnvironmentSatisfaction2 JobSatisfaction1  JobSatisfaction2  \
0                       3.0              4.0               2.0   
1                       3.0              2.0               4.0   
2                       2.0              3.0               3.0   
3                       4.0              2.0               3.0   
4                       2.0              4.0               3.0   

   JobInvolvement1  JobInvolvement2  PerformanceRating1  PerformanceRating2  \
0              2.0              2.0                 2.0                 3.0   
1              3.0              3.0                 3.0                 4.0   
2              3.0              3.0                 2.0                 2.0   
3              3.0              2.0                 3.0                 3.0   
4              3.0              4.0                 3.0                 4.0   

   Employeeturnover  
0                 0  
1                 1  
2                 0  
3                 0  
4                 1  

[5 rows x 32 columns]

In [3]:
test.head()

ID  Age  Recently_upskilled     Region  RemoteWork  \
0  142055   43                   0  Bangalore           0   
1   44367   35                   0  Hyderabad           0   
2  124144   29                   0  Bangalore           0   
3  110431   37                   0  Bangalore           0   
4  174576   23                   0  Delhi NCR           0   

   PercentSalaryIncrement  OfficeHours  StockOptionLevel  College_Tier  \
0                      13            8                 1           3.0   
1                      26            8                 2           0.0   
2                      23            7                 2           2.0   
3                      12            8                 1           1.0   
4                      23            8                 1           2.0   

   YearsSinceLastPromotion  ... TrainingTimesLastYear Department  \
0                      2.0  ...                     3         HR   
1                      2.0  ...                     3      Sales   
2                      0.0  ...                     2      Sales   
3                      2.0  ...                     0         HR   
4                      1.0  ...                     2      Sales   

   EnvironmentSatisfaction1 EnvironmentSatisfaction2  JobSatisfaction1  \
0                       4.0                      2.0               4.0   
1                       4.0                      3.0               3.0   
2                       4.0                      3.0               4.0   
3                       4.0                      3.0               3.0   
4                       4.0                      4.0               4.0   

   JobSatisfaction2  JobInvolvement1  JobInvolvement2  PerformanceRating1  \
0               4.0              3.0              3.0                 4.0   
1               3.0              4.0              4.0                 4.0   
2               3.0              3.0              2.0                 4.0   
3               3.0              4.0              3.0                 4.0   
4               2.0              4.0              2.0                 3.0   

   PerformanceRating2  
0                 4.0  
1                 3.0  
2                 3.0  
3                 3.0  
4                 3.0  

[5 rows x 31 columns]

In [4]:
test['NumCompaniesWorked'].value_counts().sum()

41836

In [5]:
test.shape

(41836, 31)

In [6]:
train.isna().sum()

ID                          0
Age                         0
Recently_upskilled          0
Region                      0
RemoteWork                  0
PercentSalaryIncrement      0
OfficeHours                 0
StockOptionLevel            0
College_Tier                0
YearsSinceLastPromotion     0
HighestEducation            0
BusinessTravel              0
JobLevel                    0
MaritalStatus               0
TotalWorkExp                0
MonthlySalary               0
yof joining                 0
YearsWithCurrManager        0
DistanceFromHome            0
NumCompaniesWorked          0
Gender                      0
TrainingTimesLastYear       0
Department                  0
EnvironmentSatisfaction1    0
EnvironmentSatisfaction2    0
JobSatisfaction1            0
JobSatisfaction2            0
JobInvolvement1             0
JobInvolvement2             0
PerformanceRating1          0
PerformanceRating2          0
Employeeturnover            0
dtype: int64

In [7]:
test.isna().sum()

ID                          0
Age                         0
Recently_upskilled          0
Region                      0
RemoteWork                  0
PercentSalaryIncrement      0
OfficeHours                 0
StockOptionLevel            0
College_Tier                0
YearsSinceLastPromotion     0
HighestEducation            0
BusinessTravel              0
JobLevel                    0
MaritalStatus               0
TotalWorkExp                0
MonthlySalary               0
yof joining                 0
YearsWithCurrManager        0
DistanceFromHome            0
NumCompaniesWorked          0
Gender                      0
TrainingTimesLastYear       0
Department                  0
EnvironmentSatisfaction1    0
EnvironmentSatisfaction2    0
JobSatisfaction1            0
JobSatisfaction2            0
JobInvolvement1             0
JobInvolvement2             0
PerformanceRating1          0
PerformanceRating2          0
dtype: int64

In [8]:
train['BusinessTravel'].value_counts()

None          68977
Frequently    19775
Sometimes      8864
Name: BusinessTravel, dtype: int64

In [9]:
train[['Recently_upskilled', 'Region', 'RemoteWork','PercentSalaryIncrement', 'OfficeHours', 'StockOptionLevel',
       'College_Tier', 'YearsSinceLastPromotion', 'HighestEducation',
       'BusinessTravel', 'JobLevel', 'MaritalStatus','YearsWithCurrManager','NumCompaniesWorked', 'Gender',
       'TrainingTimesLastYear', 'Department','EnvironmentSatisfaction1',
       'EnvironmentSatisfaction2', 'JobSatisfaction1', 'JobSatisfaction2',
       'JobInvolvement1', 'JobInvolvement2', 'PerformanceRating1',
       'PerformanceRating2', 'Employeeturnover']]=train[['Recently_upskilled', 'Region', 'RemoteWork','PercentSalaryIncrement', 'OfficeHours', 'StockOptionLevel',
       'College_Tier', 'YearsSinceLastPromotion', 'HighestEducation',
       'BusinessTravel', 'JobLevel', 'MaritalStatus','YearsWithCurrManager','NumCompaniesWorked', 'Gender',
       'TrainingTimesLastYear', 'Department','EnvironmentSatisfaction1',
       'EnvironmentSatisfaction2', 'JobSatisfaction1', 'JobSatisfaction2',
       'JobInvolvement1', 'JobInvolvement2', 'PerformanceRating1',
       'PerformanceRating2', 'Employeeturnover']].astype('object')

test[['Recently_upskilled', 'Region', 'RemoteWork','PercentSalaryIncrement', 'OfficeHours', 'StockOptionLevel',
       'College_Tier', 'YearsSinceLastPromotion', 'HighestEducation',
       'BusinessTravel', 'JobLevel', 'MaritalStatus','YearsWithCurrManager','NumCompaniesWorked', 'Gender',
       'TrainingTimesLastYear', 'Department','EnvironmentSatisfaction1',
       'EnvironmentSatisfaction2', 'JobSatisfaction1', 'JobSatisfaction2',
       'JobInvolvement1', 'JobInvolvement2', 'PerformanceRating1',
       'PerformanceRating2']]=test[['Recently_upskilled', 'Region', 'RemoteWork','PercentSalaryIncrement', 'OfficeHours', 'StockOptionLevel',
       'College_Tier', 'YearsSinceLastPromotion', 'HighestEducation',
       'BusinessTravel', 'JobLevel', 'MaritalStatus','YearsWithCurrManager','NumCompaniesWorked', 'Gender',
       'TrainingTimesLastYear', 'Department','EnvironmentSatisfaction1',
       'EnvironmentSatisfaction2', 'JobSatisfaction1', 'JobSatisfaction2',
       'JobInvolvement1', 'JobInvolvement2', 'PerformanceRating1',
       'PerformanceRating2']].astype('object')

## Transformation

In [10]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split,cross_val_score,cross_val_predict
from sklearn.preprocessing import LabelEncoder,StandardScaler
le=LabelEncoder()
ss=StandardScaler()
from sklearn import metrics

In [11]:
cat=train.drop(['Employeeturnover'],axis=1).select_dtypes(include='object')
catdum=pd.get_dummies(cat,drop_first=True)
catdum.shape

(97616, 113)

In [12]:
num=train.drop(['ID'],axis=1).select_dtypes(include=np.number)
num.head()

Age  TotalWorkExp  MonthlySalary  yof joining  DistanceFromHome
0   33             4          12610            5                 2
1   34             8          54840            5                 4
2   33             8          22070            6                 8
3   38            26          43672            3                 3
4   28             3          68178            5                 7

In [13]:
num.shape

(97616, 5)

In [14]:
num[['Age','MonthlySalary','yof joining','DistanceFromHome','TotalWorkExp']].skew()

Age                 0.442330
MonthlySalary       1.393678
yof joining         2.013084
DistanceFromHome    0.994063
TotalWorkExp        1.211364
dtype: float64

In [15]:
np.log(num[['Age','MonthlySalary','yof joining','DistanceFromHome','TotalWorkExp']]).skew()

Age                -0.155728
MonthlySalary       0.287770
yof joining         0.051439
DistanceFromHome   -0.288751
TotalWorkExp             NaN
dtype: float64

In [16]:
np.cbrt(num[['Age','MonthlySalary','yof joining','DistanceFromHome','TotalWorkExp']]).skew()

Age                 0.053205
MonthlySalary       0.686432
yof joining         0.639678
DistanceFromHome    0.168365
TotalWorkExp       -0.682275
dtype: float64

In [17]:
np.sqrt(num[['Age','MonthlySalary','yof joining','DistanceFromHome','TotalWorkExp']]).skew()

Age                 0.153802
MonthlySalary       0.875289
yof joining         0.958636
DistanceFromHome    0.392931
TotalWorkExp        0.142190
dtype: float64

In [18]:
num[['MonthlySalary','yof joining']]=np.log(num[['MonthlySalary','yof joining']])

In [19]:
num[['Age','DistanceFromHome']]=np.cbrt(num[['Age','DistanceFromHome']])
num[['TotalWorkExp']]=np.sqrt(num['TotalWorkExp'])

In [20]:
num[num.columns]=ss.fit_transform(num)

In [21]:
X=pd.concat([catdum,num],axis=1)
X.shape

(97616, 118)

In [22]:
y=train['Employeeturnover'].astype('int')

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [24]:
DT=DecisionTreeClassifier()
DT.fit(X_train,y_train)

DecisionTreeClassifier()

In [25]:
pred_test=DT.predict(X_test)

In [26]:
metrics.confusion_matrix(y_test,pred_test)

array([[20951,  2494],
       [ 2318,  3522]], dtype=int64)

In [27]:
print(metrics.classification_report(y_test,pred_test))

              precision    recall  f1-score   support

           0       0.90      0.89      0.90     23445
           1       0.59      0.60      0.59      5840

    accuracy                           0.84     29285
   macro avg       0.74      0.75      0.75     29285
weighted avg       0.84      0.84      0.84     29285



In [28]:
from sklearn.ensemble import AdaBoostClassifier

In [29]:
ADA=AdaBoostClassifier(n_estimators=150,learning_rate=.1)
ADA.fit(X_train,y_train)

AdaBoostClassifier(learning_rate=0.1, n_estimators=150)

In [30]:
pred_test=ADA.predict(X_test)
print(metrics.classification_report(y_test,pred_test))
metrics.confusion_matrix(y_test,pred_test)

              precision    recall  f1-score   support

           0       0.82      0.99      0.90     23445
           1       0.78      0.15      0.25      5840

    accuracy                           0.82     29285
   macro avg       0.80      0.57      0.58     29285
weighted avg       0.81      0.82      0.77     29285



array([[23191,   254],
       [ 4960,   880]], dtype=int64)

In [31]:
from xgboost import XGBClassifier

In [32]:
XGB=XGBClassifier(use_label_encoder=False,gamma=1,learning_rate=.01,min_child_weight=.5,n_estimator=300)
XGB.fit(X_train,y_train)

[00:30:17] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:541: 
Parameters: { n_estimator } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[00:30:17] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=1, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.01, max_delta_step=0, max_depth=6,
              min_child_weight=0.5, missing=nan, monotone_constraints='()',
              n_estimator=300, n_estimators=100, n_jobs=4, num_parallel_tree=1,
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              subsample=1, tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None)

In [33]:
pred_test=XGB.predict(X_test)
print(metrics.classification_report(y_test,pred_test))
metrics.confusion_matrix(y_test,pred_test)

              precision    recall  f1-score   support

           0       0.84      0.98      0.91     23445
           1       0.74      0.28      0.40      5840

    accuracy                           0.84     29285
   macro avg       0.79      0.63      0.65     29285
weighted avg       0.82      0.84      0.81     29285



array([[22868,   577],
       [ 4219,  1621]], dtype=int64)

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
RF=RandomForestClassifier(n_estimators=350,max_depth=8,)
RF.fit(X_train,y_train)

RandomForestClassifier(max_depth=8, n_estimators=350)

In [36]:
pred_test=RF.predict(X_test)

print(metrics.classification_report(y_test,pred_test))
metrics.confusion_matrix(y_test,pred_test)


              precision    recall  f1-score   support

           0       0.82      1.00      0.90     23445
           1       0.92      0.09      0.17      5840

    accuracy                           0.82     29285
   macro avg       0.87      0.55      0.53     29285
weighted avg       0.84      0.82      0.75     29285



array([[23394,    51],
       [ 5287,   553]], dtype=int64)

# ------------------------------------------------------------------------------------------

In [37]:
c0=test.select_dtypes(include='object')
c0dum=pd.get_dummies(c0,drop_first=True)
c0dum.shape

(41836, 114)

In [38]:
len(c0dum.columns)

114

In [39]:
len(catdum.columns)

113

In [40]:
train['NumCompaniesWorked'].value_counts()

1.0     48487
2.0     12710
3.0      8953
4.0      7186
5.0      6126
6.0      4268
7.0      3690
8.0      3330
9.0      1807
10.0     1059
Name: NumCompaniesWorked, dtype: int64

In [41]:
test['NumCompaniesWorked']=test['NumCompaniesWorked'].mask(test['NumCompaniesWorked']==0,1)

In [42]:
c0=test.select_dtypes(include='object')
c0dum=pd.get_dummies(c0,drop_first=True)
c0dum.shape

(41836, 113)

In [43]:
n0=test.drop(['ID'],axis=1).select_dtypes(include=np.number)
n0.head()

Age  TotalWorkExp  MonthlySalary  yof joining  DistanceFromHome
0   43            21          20730            5                 3
1   35            12         131420           11                11
2   29             9          46481            6                 7
3   37            18         106480            4                 9
4   23             4          41890            6                 8

In [44]:
n0.shape

(41836, 5)

In [45]:
n0[['Age','MonthlySalary','yof joining','DistanceFromHome','TotalWorkExp']].skew()

Age                 0.424402
MonthlySalary       1.407018
yof joining         1.988753
DistanceFromHome    1.010283
TotalWorkExp        1.125518
dtype: float64

In [46]:
np.log(n0[['Age','MonthlySalary','yof joining','DistanceFromHome','TotalWorkExp']]).skew()

Age                -0.182915
MonthlySalary       0.297544
yof joining         0.084193
DistanceFromHome   -0.280451
TotalWorkExp             NaN
dtype: float64

In [47]:
np.cbrt(n0[['Age','MonthlySalary','yof joining','DistanceFromHome','TotalWorkExp']]).skew()

Age                 0.029463
MonthlySalary       0.698744
yof joining         0.664236
DistanceFromHome    0.177431
TotalWorkExp       -0.568933
dtype: float64

In [48]:
np.sqrt(n0[['Age','MonthlySalary','yof joining','DistanceFromHome','TotalWorkExp']]).skew()

Age                 0.131626
MonthlySalary       0.888274
yof joining         0.974886
DistanceFromHome    0.403323
TotalWorkExp        0.152297
dtype: float64

In [49]:
n0[['MonthlySalary','yof joining']]=np.log(n0[['MonthlySalary','yof joining']])

In [50]:
n0[['Age','DistanceFromHome']]=np.cbrt(n0[['Age','DistanceFromHome']])
n0[['TotalWorkExp']]=np.sqrt(n0['TotalWorkExp'])

In [51]:
n0[n0.columns]=ss.transform(n0)


In [52]:
X0=pd.concat([c0dum,n0],axis=1)
X0.shape

(41836, 118)

In [53]:
submission=test[['ID']].copy(deep=True)
submission['Employeeturnover']=XGB.predict(X0)

In [54]:
submission.set_index('ID').to_csv('Submissionfile.csv')

In [55]:
submission['Employeeturnover'].value_counts()

0    37134
1     4702
Name: Employeeturnover, dtype: int64

In [56]:
submission['Employeeturnover'].value_counts()

0    37134
1     4702
Name: Employeeturnover, dtype: int64

In [57]:
train['Employeeturnover'].value_counts()

0    78299
1    19317
Name: Employeeturnover, dtype: int64